### ISSUE TITLE
When inserting the URL in an e-mail there should be more descriptive writing about the site with the logo

### ISSUE THREAD

**Issue by AviMaayan** [MaayanLab/datacrossways#11]
Right now you get this:
<img width="739" alt="Screenshot 2024-07-02 at 12 16 45 PM" src="https://github.com/MaayanLab/datacrossways/assets/12749033/f86bf0eb-89c7-46d0-a91b-1f46bbf0ea5d">

**Comment by heesukim628** [comment]
Maybe we can use:
Innovative Health Data Hub (IHDH) provides a unified resource to deposit, archive, and share data collected by researchers funded by the Steven & Alexandra Cohen Foundation.
