### ISSUE TITLE
When login out the screen should show a more professional response

### ISSUE THREAD

**Issue by AviMaayan** [MaayanLab/datacrossways#13]
<img width="477" alt="Screenshot 2024-09-29 at 4 07 20 PM" src="https://github.com/user-attachments/assets/a6cd9a34-10da-4930-80e6-dd4b459b5a1f">

**Comment by lachmann12** [comment]
It should load this and redirect you to the homepage so I can't reproduce this behaviour:
<img width="1728" alt="image" src="https://github.com/user-attachments/assets/908e05b7-31df-4548-b108-0664a60a2627">
