### ISSUE TITLE
Once you are logged in with Google, the favicon is the Google favicon, it should be the IHDH favicon

### ISSUE THREAD

**Issue by AviMaayan** [MaayanLab/datacrossways#16]

**Comment by lachmann12** [comment]
I can't reproduce this error. It might be a caching issue?
<img width="815" alt="image" src="https://github.com/user-attachments/assets/71ab6c70-a5cb-4f4d-8af1-542bd08df244">

**Comment by lachmann12** [comment]
i see, it is the home page only that shows this behaviour

**Comment by lachmann12** [comment]
fixed
