### ISSUE TITLE
Tried adding institution name for my account and received "there was a problem updating the user"

### ISSUE THREAD

**Issue by AviMaayan** [MaayanLab/datacrossways#2]
<img width="597" alt="Screen Shot 2023-11-05 at 11 29 32 PM" src="https://github.com/MaayanLab/datacrossways/assets/12749033/2eee60db-ae65-498a-97ea-b77cbe11bf25">
This is not because the string is too lang, I also tried "ISMMS"

**Comment by lachmann12** [comment]
only admin was allowed to modify users. Users can now modify themselfs
