### ISSUE TITLE
The site does not have a footer after logging in. 

### ISSUE THREAD

**Issue by AviMaayan** [MaayanLab/datacrossways#4]

**Comment by lachmann12** [comment]
To confirm: you want 
![image](https://github.com/MaayanLab/datacrossways/assets/32603869/46e701e4-c1ca-4285-98e4-5a2631b90be5)
 under every page of the website?

**Comment by lachmann12** [comment]
(it will be 2023)

**Comment by lachmann12** [comment]
i mean full footer: 
![image](https://github.com/MaayanLab/datacrossways/assets/32603869/a3ab501f-d251-4613-a367-71693a9fa227)
